<?php
if($_GET['option'] === 'default') {
$settings = [
'general-menu' => '',
'general-logo' => SMM_PLUGIN_URL . 'assets/img/logo.png',
'general-menu-bar-color' => '#ffffff',
'general-menu-container-color' => '#ffffff',
'general-overlay-color' => '#ffffff',
'general-icon-parent' => 'fa-caret-right',
'sticky' => 'on',
'sticky-logo' => SMM_PLUGIN_URL . 'assets/img/logo.png',
'topbar-display' => 'off',
'topbar-layout' => '0',
'topbar-menu' => '',
'topbar-backgroundcolor' => '#fff',
'topbar-text' => '',
'mainbar-layout' => '0',
'container-language' => 'off',
'container-layout' => '0',
'container-desc' => '',
'container-content' => '' ,
'hamburger' => 'hamburger--elastic',
'social-on' => 'on',
'social-icons' => '[{"icon":"fa-facebook","link":"facebook.pl"},{"icon":"fa-twitter-square","link":"twitter.pl"},{"icon":"fa-youtube-play","link":"youtube.com"}]',
'icons-left' => '[{"icon":"fa-glass","link":""}]',
'icons-right' => '[{"icon":"fa-glass","link":""}]',
'typography-bg-active-color' => '#1e73be',
'typography-font-color' => '#000000',
'typography-active-font-color' => '#ffffff',
'typography-fonttype' => '{"fonts":{},"selectorSuffix":"-main34","apiKey":"","options":{"pickerId":"main34","families":[],"categories":[],"scripts":["latin"],"variants":["regular"],"limit":30,"sort":"alphabet"},"activeFontFamily":"Open Sans"}',
'typography-fonttype-title' => '{"fonts":{},"selectorSuffix":"-main35","apiKey":"","options":{"pickerId":"main35","families":[],"categories":[],"scripts":["latin"],"variants":["regular"],"limit":30,"sort":"alphabet"},"activeFontFamily":"Open Sans"}',
'typography-fontsize-menu-itmes' => '18',
'hide-desktop-menu' => '#masthead',
'breakpoint' => '768',
'activation-code' => '',
'google-api' => ''
];
} else {
$settings = [
'general-menu' => '',
'general-logo' => SMM_PLUGIN_URL . 'assets/img/logo.png',
'general-menu-bar-color' => '#000',
'general-menu-container-color' => '#ffffff',
'general-overlay-color' => '#ffffff',
'general-icon-parent' => 'fa-caret-right',
'sticky' => 'on',
'sticky-logo' => SMM_PLUGIN_URL . 'assets/img/logo.png',
'topbar-display' => 'off',
'topbar-layout' => '0',
'topbar-menu' => '',
'topbar-backgroundcolor' => '#fff',
'topbar-text' => '',
'mainbar-layout' => '0',
'container-language' => 'off',
'container-layout' => '0',
'container-desc' => '',
'container-content' => '' ,
'hamburger' => 'hamburger--elastic',
'social-on' => 'on',
'social-icons' => '[{"icon":"fa-facebook","link":"facebook.pl"},{"icon":"fa-twitter-square","link":"twitter.pl"},{"icon":"fa-youtube-play","link":"youtube.com"}]',
'icons-left' => '[{"icon":"fa-glass","link":""}]',
'icons-right' => '[{"icon":"fa-glass","link":""}]',
'typography-bg-active-color' => '#1e73be',
'typography-font-color' => '#000000',
'typography-active-font-color' => '#ffffff',
'typography-fonttype' => '{"fonts":{},"selectorSuffix":"-main34","apiKey":"","options":{"pickerId":"main34","families":[],"categories":[],"scripts":["latin"],"variants":["regular"],"limit":30,"sort":"alphabet"},"activeFontFamily":"Open Sans"}',
'typography-fonttype-title' => '{"fonts":{},"selectorSuffix":"-main35","apiKey":"","options":{"pickerId":"main35","families":[],"categories":[],"scripts":["latin"],"variants":["regular"],"limit":30,"sort":"alphabet"},"activeFontFamily":"Open Sans"}',
'typography-fontsize-menu-itmes' => '18',
'hide-desktop-menu' => '#masthead',
'breakpoint' => '768',
'activation-code' => '',
'google-api' => ''
];
}
update_option('super_mobile_settings', $settings);
wp_redirect(admin_url('admin.php?page=super-menu'));
exit;